Add helpers for wheel event
seed-rs/seed pull request #596
Opened 2021-04-05 12:09 UTC by msuesskraut

- add helpers
  - `wheel_ev` - see `keyboard_ev`
  - `to_wheel_event` - see `to_keyboard_event`
- use `wheel_ev` in `canvas` example
  - scrolling the mouse wheel while the mouse pointer is within the canvas zooms the rectangle

2021-04-05 18:11 UTC, MartinKavik requested changes
Thanks for the PR!
I've written some code review comments, please look at them.
And please update also CHANGELOG.md.

2021-04-05 18:11 UTC, MartinKavik commented on examples/canvas/src/lib.rs
> +        }
If we update `wheel_ev` (see the comment below), then we can rewrite it to:
```suggestion
        Msg::WheelDeltaY(delta_y) => {
            model.zoom += if delta_y < 0. { -0.1  } else { 0.1 };
        }
```

2021-04-06 20:50 UTC, msuesskraut commented
I'm busy the next few days. I'll come back to this PR at the next weekend.

2021-04-10 10:51 UTC, msuesskraut commented on examples/canvas/src/lib.rs
> +            }),
I followed you suggestion, but instead of passing the delta as int around a new enum is now used.

2021-04-10 10:51 UTC, msuesskraut commented on examples/canvas/src/lib.rs
> +    Zoom(WheelEvent),
New `Zoom` enum is now passed around to communicatt the direction.

2021-04-10 11:25 UTC, msuesskraut commented
I applied your suggested changes with slightly different and also extended the change log.

Can you please have another look at this PR.

Thanks, Martin

2021-04-10 11:59 UTC, MartinKavik approved these changes

2021-04-10 11:59 UTC, merged